# Generated by Django 6.0.6 on 2026-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 01, 02', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='e.g. Company Website', max_length=100)),
                ('description', models.TextField()),
                ('tech', models.CharField(help_text='Tools and features, e.g. Python · Django · Bootstrap 5', max_length=200)),
                ('link', models.URLField(blank=True, help_text='Link to live project or #', null=True)),
                ('image', models.CharField(help_text='Path to image, e.g. /images/omnexaai.png', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Determines the display order (0 is first)')),
            ],
            options={
                'verbose_name': 'Work Project',
                'verbose_name_plural': 'Work Projects',
                'ordering': ['order', 'number'],
            },
        ),
    ]
